name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  quality:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v3

      - uses: edgedb/setup-edgedb@v1

      - run: edgedb project init --non-interactive --server-start-conf=manual --server-instance=tests
        working-directory: tests

      - run: edgedb instance start --instance tests
        working-directory: tests

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: snok/install-poetry@v1.3
        with:
          version: 1.4.0

      - name: Install dependencies
        run: poetry install

      - name: Run linter
        run: poetry run ruff check .

      - name: Run mypy
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest
        env:
          PYTHONPATH: ..
        working-directory: tests

      - name: Fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/edgeql-qb\/edgeql-qb\//\/github\/workspace\//g' tests/artefacts/coverage.xml

      - name: SonarCloud Scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
